1. Create len(10) integer array filled with zeros

In [ ]:
import numpy as np
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Create 3x5 floating point array filled with ones

In [ ]:
b = np.full((3, 5), 1.)
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

3. Create 3x5 array filled with 3.14

In [ ]:
c = np.full((3, 5), 3.14)
c

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

4. Create an array filled with a linear space starting at 0, ending at 20, stepping by 2

In [ ]:
d = np.linspace(0, 20, 11)
d

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

5. Create an array of five values evenly spaced between 0 and 1

In [ ]:
e = np.linspace(0, 1, 5)
e

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 3x3 array of uniformly distributed random (0, 1)

In [ ]:
f = np.random.uniform(0, 1, 9).reshape(3, 3)
f

array([[0.69299116, 0.14291029, 0.6462318 ],
       [0.4121466 , 0.73160465, 0.62483687],
       [0.42139311, 0.080061  , 0.7884739 ]])

7. Create a 3x3 array of with mean 0 and standard deviation 1

In [ ]:
import numpy as np
g = np.random.randn(3, 3)
g

array([[ 0.68806214, -1.12769223, -1.627787  ],
       [ 1.62286226,  1.80097224,  0.43173688],
       [ 0.08004238, -1.10396677, -1.37505754]])

8. Create a 3x3 array of random integers in the interval [0, 10]

In [ ]:
h = 10 * np.random.random_sample((3, 3))
h

array([[3.0993143 , 0.82286682, 4.53161645],
       [6.56573068, 0.82138844, 2.59801815],
       [0.38495789, 0.02060971, 2.44207326]])

9. Create a 3x3 identity matrix

In [ ]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])